services:
  server:
    build:
      context: .
    restart: unless-stopped
    command: ["bun", "server-dev"]
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USER=rinha
      - DATABASE_PASSWORD=rinha
      - DATABASE_NAME=rinha
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
    networks:
      - rinha

  worker:
    build:
      context: .
    restart: unless-stopped
    command: ["bun", "worker-dev"]
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USER=rinha
      - DATABASE_PASSWORD=rinha
      - DATABASE_NAME=rinha
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
    networks:
      - rinha

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - rinha

  redis-insight:
    image: redis/redisinsight:2.60
    ports:
      - "5540:5540"
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - redisinsight_data:/data
    networks:
      - rinha

  database:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rinha"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - rinha

  pgadmin:
    image: dpage/pgadmin4:9.4
    environment:
      PGADMIN_DEFAULT_EMAIL: "rinha@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "rinha"
    ports:
      - "8080:80"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - rinha

volumes:
  pg_data:
  redis_data:
  redisinsight_data:

networks:
  rinha:
