services:
  api:
    build:
      context: .
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "9999:9999"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PAYMENTS_QUEUE_NAME=payments_queue
      - REDIS_PAYMENTS_QUEUE_JOB=payments
      - REDIS_PROCESSORS_STATUS_KEY=payments:health_status
      - REDIS_PAYMENTS_DEFAULT_KEY=payments:default
      - REDIS_PAYMENTS_FALLBACK_KEY=payments:key
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - rinha
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "1.2"
          memory: "290MB"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "60MB"

volumes:
  redis_data:

networks:
  rinha:
    driver: bridge
  payment-processor:
    external: true
