services:
  api_1:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
  api_2:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app